Add Finalizer Safety Analysis (FSA)
This change allows us to check at compile-time whether a `Gc<T>` is safe to
finalize if `T` implements `Drop`. The algorithm works roughly as follows:

    1. Check if `T: FinalizerSafe`, which is set up to have all
       the same bounds as `T: Send + Sync` in the standard library.

    2. If `T: !FinalizerSafe`, look at all the drop methods that `T`
       needs to call. That means `T`s drop method, and any drop methods
       of `T`s component types.

    3. Look at the MIR for each of these drop methods, if any of them
       contain a projection into a field which is not `FinalizerSafe`,
       then emit a compiler error, showing the exact line inside `drop`
       which is unsound.

This makes `Gc` much safer to use, because there are types which
implement `Drop` which are not `Send + Sync`, but they don't do anything
in `Drop` in a thread-unsafe way. We can now make use of Rust's ability
to detect races at compile-time to ensure we have safe drop calls inside
finalizers.

This also lets us prevent users from derefing `Gc` fields inside
finalizers, as we mark `Gc` as `!FinalizerSafe` *but* leave it `Send +
Sync` if its contents are.

This can be better understood with an example. Consider the following
Rust program which performs a non-thread-safe operation inside its
`drop` method.

```rust

    struct S(Rc<Cell<String>>);

    impl !std::marker::FinalizerSafe for S{}

    impl Drop for S {
        fn drop(&mut self) {
            self.0.replace("World".to_string());
        }
    }

    fn main() {
        let rc = Rc::new(Cell::new("Hello".to_string()));
        let gc = Gc::new(S(Rc::clone(&rc)));
    }

```

This will give the following compiler error:

error: `S(Rc::clone(&rc))` cannot be safely finalized.
  --> src/main.rs:19:22
   |
13 |         self.0.replace("World".to_string());
   |         -----------------------------------
   |         |
   |         caused by the expression in `fn drop(&mut)` here because
   |         it uses a type which is not safe to use in a finalizer.
...
19 |     let gc = Gc::new(S(Rc::clone(&rc)));
   |                      ^^^^^^^^^^^^^^^^^ has a drop method which cannot be safely finalized.
   |
   = help: `Gc` runs finalizers on a separate thread, so drop methods
           must only use values whose types implement `FinalizerSafe`.